/**
 * Generate WHMCS_WEBHOOK_SECRET (if missing) and sync WHMCS hook local config.
 *   npm run setup:webhook
 */
import crypto from 'crypto'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const envPath = path.join(root, '.env')
const localPhp = path.join(root, 'whmcs/includes/hooks/printablelistings.local.php')

function loadEnvLines(file) {
  if (!fs.existsSync(file)) return []
  return fs.readFileSync(file, 'utf8').split('\n')
}

function readEnv(file) {
  const env = {}
  for (const line of loadEnvLines(file)) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim()
  }
  return env
}

function writeEnvKey(file, key, value) {
  const lines = loadEnvLines(file)
  let found = false
  const out = lines.map((line) => {
    if (line.startsWith(`${key}=`)) {
      found = true
      return `${key}=${value}`
    }
    return line
  })
  if (!found) out.push(`${key}=${value}`)
  fs.writeFileSync(file, out.join('\n'))
}

if (!fs.existsSync(envPath)) {
  console.error('No .env file — copy .env.example to .env first.')
  process.exit(1)
}

const env = readEnv(envPath)
let secret = env.WHMCS_WEBHOOK_SECRET?.trim()
if (!secret) {
  secret = crypto.randomBytes(32).toString('hex')
  writeEnvKey(envPath, 'WHMCS_WEBHOOK_SECRET', secret)
  console.log('✓ Generated WHMCS_WEBHOOK_SECRET in .env')
} else {
  console.log('✓ Using existing WHMCS_WEBHOOK_SECRET from .env')
}

const siteUrl = (env.SITE_URL ?? 'https://printablelistings.xyz').replace(/\/$/, '')
const apiUrl = `${siteUrl}/api/whmcs/webhook`

const php = `<?php
/**
 * Auto-generated by npm run setup:webhook — do not commit (gitignored).
 * Install on WHMCS: /var/www/whmcs/includes/hooks/printablelistings.local.php
 */
if (!defined('WHMCS')) {
    die('This file cannot be accessed directly');
}

define('PRINTABLELISTINGS_API_URL', '${apiUrl}');
define('PRINTABLELISTINGS_WEBHOOK_SECRET', '${secret}');
`

fs.writeFileSync(localPhp, php)
console.log(`✓ Wrote ${path.relative(root, localPhp)}`)
console.log('')
console.log('On billing.nexlify.live, copy both files to /var/www/whmcs/includes/hooks/:')
console.log('  printablelistings-invoice-paid.php')
console.log('  printablelistings.local.php')
console.log('')
console.log('Or from the VPS (if marketplace-hub is deployed there):')
console.log('  bash deploy/install-whmcs-hook.sh')
